export default {
  SIDEMENU: require('../assets/icon/sidemenuicon3x.png'),
  ATTENDANCE_REGISTRATION: require('../assets/icon/attendance.png'),
  NEWS: require('../assets/icon/news.png'),
  LOCATION: require('../assets/icon/location.png'),
  GALLERY: require('../assets/icon/gallery.png'),
  CALENDAR: require('../assets/icon/calendar.png'),
  LIST: require('../assets/icon/list.png'),
  SIDEMENU_1X: require('../assets/icon/sidemenuicon1x.png'),
  SIDEMENU_2X: require('../assets/icon/sidemenuicon2x.png'),
  SIDEMENU_3X: require('../assets/icon/sidemenuicon3x.png'),
  SCHEDULE: require('../assets/icon/schedule.png'),
  SPONSOR: require('../assets/icon/sponsor.png'),
  CONTACT: require('../assets/icon/contact.png'),
  TECH_CAFE: require('../assets/icon/tech_cafe.png'),
  FOOD_TRUCK: require('../assets/icon/food-truck.png'),
  EXHIBITOR_APPLICATION: require('../assets/icon/exhibitor.png'),
  PROGRAM_GUIDE: require('../assets/icon/guide.png'),
  HOME_SCREEN: require('../assets/imgs/homeScreenImage.png'),
  PBOIS_ABOUT: require('../assets/imgs/about_pbios.png'),
  HOME_ICON: require('../assets/icon/home.png'),
  INFO_ICON: require('../assets/icon/info-icon.png'),
  PHOTO_GALLERY: require('../assets/icon/photo-gallery.png'),
  MAIL: require('../assets/icon/mail.png'),
  CONTACT_ICON: require('../assets/icon/contact-phone.png'),
  AMTECH_LOGO: require('../assets/imgs/AmtechLogo.png'),
};
