import Matrics from './Matrics';

const typography = {
  lineHeights: {
    xxs: '1em',
    xs: '1.125em',
    sm: '1.25em',
    md: '1.375em',
    lg: '1.5em',
    xl: '1.75em',
    '2xl': '2em',
    '3xl': '2.5em',
    '4xl': '3em',
    '5xl': '4em',
  },
  fontFamily: {
    Jost: {
      Thin: 'Jost-Thin',
      ExtraLight: 'Jost-ExtraLight',
      Light: 'Jost-Light',
      Regular: 'Jost-Regular',
      Medium: 'Jost-Medium',
      SemiBold: 'Jost-SemiBold',
      Bold: 'Jost-Bold',
      ExtraBold: 'Jost-ExtraBold',
      Black: 'Jost-Black',
      ThinItalic: 'Jost-ThinItalic',
      ExtraLightItalic: 'Jost-ExtraLightItalic',
      LightItalic: 'Jost-LightItalic',
      Italic: 'Jost-Italic',
      MediumItalic: 'Jost-MediumItalic',
      SemiBoldItalic: 'Jost-SemiBoldItalic',
      BoldItalic: 'Jost-BoldItalic',
      ExtraBoldItalic: 'Jost-ExtraBoldItalic',
      BlackItalic: 'Jost-BlackItalic',
    },
    NotoSans: {
      Regular: 'NotoSans-Regular',
      Bold: 'NotoSans-Bold',
      Italic: 'NotoSans-Italic',
      BoldItalic: 'NotoSans-BoldItalic',
    },
  },
  fontSizes: {
    fs6: Matrics.ms(6),
    fs7: Matrics.ms(7),
    fs8: Matrics.ms(8),
    fs9: Matrics.ms(9),
    fs10: Matrics.ms(10),
    fs11: Matrics.ms(11),
    fs12: Matrics.ms(12),
    fs13: Matrics.ms(13),
    fs14: Matrics.ms(14),
    fs15: Matrics.ms(15),
    fs16: Matrics.ms(16),
    fs17: Matrics.ms(17),
    fs18: Matrics.ms(18),
    fs19: Matrics.ms(19),
    fs20: Matrics.ms(20),
    fs21: Matrics.ms(21),
    fs22: Matrics.ms(22),
    fs24: Matrics.ms(24),
    fs30: Matrics.ms(30),
    fs36: Matrics.ms(36),
  },
  margin: {
    mn10: Matrics.ms(10),
    mn12: Matrics.ms(12),
    mn14: Matrics.ms(14),
    mn16: Matrics.ms(16),
    mn18: Matrics.ms(18),
    mn20: Matrics.ms(20),
    mn24: Matrics.ms(24),
    mn30: Matrics.ms(30),
    mn36: Matrics.ms(36),
  },
  padding: {
    pg10: Matrics.ms(10),
    pg12: Matrics.ms(12),
    pg14: Matrics.ms(14),
    pg16: Matrics.ms(16),
    pg18: Matrics.ms(18),
    pg20: Matrics.ms(20),
    pg24: Matrics.ms(24),
    pg30: Matrics.ms(30),
    pg36: Matrics.ms(36),
  },
};

export default typography;
